/* eslint-disable react/no-unescaped-entities */
import type { MetaFunction } from '@vercel/remix';
import { Link } from '@remix-run/react';

export const meta: MetaFunction = () => [
  { title: 'Terms of Service | Nanny — Plant-Based Hospitality OS' },
  { name: 'description', content: 'Terms of Service for the Nanny plant-based hospitality platform.' },
];

export default function TermsOfService() {
  return (
    <div className="min-h-screen" style={{ backgroundColor: '#FAFAF7', color: '#1A1A18' }}>
      <div className="mx-auto max-w-3xl px-6 py-16">
        <Link
          to="/nanny"
          className="mb-8 inline-flex items-center gap-2 text-sm font-medium"
          style={{ color: '#2D5016' }}
        >
          ← Back to Nanny
        </Link>

        <h1 className="mb-2 text-4xl font-bold tracking-tight" style={{ color: '#2D5016' }}>
          Terms of Service
        </h1>
        <p className="mb-12 text-sm text-gray-500">Effective date: June 1, 2026 · Last updated: June 1, 2026</p>

        <Section title="1. Introduction">
          <p>
            Welcome to Nanny, a premium plant-based hospitality intelligence platform operated by Nanny Technologies,
            Inc. ("Nanny," "we," "our," or "us"). By accessing or using Nanny at any of our web properties, mobile
            applications, or APIs (collectively, the "Service"), you agree to be bound by these Terms of Service
            ("Terms"). Please read them carefully. If you do not agree to these Terms, you may not use the Service.
          </p>
        </Section>

        <Section title="2. Description of Services">
          <p>
            Nanny provides an AI-powered hospitality operating system designed for ghost kitchens, private chefs, and
            event caterers specializing in plant-based cuisine. Our Service includes:
          </p>
          <ul className="mt-3 list-inside list-disc space-y-1 pl-2">
            <li>AI-generated menus tailored to event parameters, dietary needs, and cuisine preferences</li>
            <li>Provisioning and ingredient sourcing lists with vendor recommendations</li>
            <li>Service runbook generation for event execution</li>
            <li>Voice-activated command dispatch for kitchen environments</li>
            <li>Visual ingredient analysis via image upload</li>
            <li>Creative marketing asset generation</li>
          </ul>
          <p className="mt-3">
            Features are subject to change. We reserve the right to modify, suspend, or discontinue any aspect of the
            Service at any time with reasonable notice.
          </p>
        </Section>

        <Section title="3. Subscription & Billing">
          <p>
            Nanny offers subscription-based access at tiers including Starter, Professional, and Enterprise. Billing is
            processed monthly or annually in advance. All fees are in USD and are non-refundable except where required
            by applicable law.
          </p>
          <p className="mt-3">
            You authorize us to charge your payment method on a recurring basis until you cancel. Cancellation takes
            effect at the end of the current billing period. We may change pricing with 30 days' notice. Continued use
            after a price change constitutes acceptance of the new pricing.
          </p>
          <p className="mt-3">
            Free trials, if offered, automatically convert to paid subscriptions unless cancelled before the trial
            period ends. Enterprise agreements are governed by separate order forms.
          </p>
        </Section>

        <Section title="4. Data & Privacy">
          <p>
            Your use of the Service is also governed by our{' '}
            <Link to="/nanny/privacy" style={{ color: '#2D5016', textDecoration: 'underline' }}>
              Privacy Policy
            </Link>
            , which is incorporated into these Terms by reference. By using the Service, you consent to the collection,
            use, and sharing of your data as described therein.
          </p>
          <p className="mt-3">
            You retain ownership of all content you submit to the Service, including menus, event details, and
            photographs. You grant Nanny a limited, non-exclusive license to process this content solely to deliver the
            Service to you. We do not sell your data to third parties.
          </p>
        </Section>

        <Section title="5. AI-Generated Content Disclaimer">
          <p>
            Content generated by Nanny's AI systems—including menus, provisioning lists, service runbooks, and creative
            briefs—is produced by large language models and may contain errors, omissions, or inaccuracies. AI-generated
            content is intended as a starting point for professional judgment, not a substitute for it.
          </p>
          <p className="mt-3">
            <strong>You are solely responsible</strong> for reviewing all AI-generated content before using it in a
            professional capacity. Nanny does not warrant that AI output is accurate, complete, safe, legal, or fit for
            any particular purpose. Verify allergen information, nutritional claims, and food safety guidance
            independently and with qualified professionals.
          </p>
          <p className="mt-3">
            AI models are provided by third-party providers (currently Anthropic and OpenAI). Their use is subject to
            those providers' own terms. We make no representation regarding the outputs of third-party AI systems.
          </p>
        </Section>

        <Section title="6. Limitation of Liability">
          <p>
            TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, NANNY AND ITS OFFICERS, DIRECTORS, EMPLOYEES, LICENSORS,
            AND SERVICE PROVIDERS SHALL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, EXEMPLARY,
            OR PUNITIVE DAMAGES, INCLUDING BUT NOT LIMITED TO LOST PROFITS, LOST DATA, PERSONAL INJURY, OR PROPERTY
            DAMAGE, ARISING FROM YOUR USE OF OR INABILITY TO USE THE SERVICE.
          </p>
          <p className="mt-3">
            IN NO EVENT SHALL NANNY'S TOTAL LIABILITY TO YOU FOR ALL CLAIMS ARISING FROM OR RELATED TO THESE TERMS OR
            THE SERVICE EXCEED THE GREATER OF (A) THE AMOUNTS PAID BY YOU TO NANNY IN THE TWELVE MONTHS PRIOR TO THE
            CLAIM OR (B) ONE HUNDRED US DOLLARS ($100).
          </p>
          <p className="mt-3">
            Some jurisdictions do not allow the exclusion or limitation of certain damages. In such jurisdictions,
            Nanny's liability shall be limited to the fullest extent permitted by law.
          </p>
        </Section>

        <Section title="7. Governing Law">
          <p>
            These Terms are governed by and construed in accordance with the laws of the State of Delaware, United
            States, without regard to its conflict of law provisions. Any dispute arising from these Terms shall be
            subject to the exclusive jurisdiction of the state and federal courts located in Delaware.
          </p>
          <p className="mt-3">
            If you are a consumer in the European Union, you may also have the right to bring disputes before the courts
            of your country of residence and to pursue resolution via the European Commission's Online Dispute
            Resolution platform at https://ec.europa.eu/consumers/odr.
          </p>
        </Section>

        <Section title="8. Contact">
          <p>If you have questions about these Terms, please contact us at:</p>
          <address className="mt-3 not-italic">
            <strong>Nanny Technologies, Inc.</strong>
            <br />
            Legal Department
            <br />
            Email:{' '}
            <a href="mailto:legal@nanny.kitchen" style={{ color: '#2D5016', textDecoration: 'underline' }}>
              legal@nanny.kitchen
            </a>
            <br />
            We aim to respond to all legal inquiries within 5 business days.
          </address>
        </Section>

        <div className="mt-16 border-t pt-8" style={{ borderColor: '#E5E5E0' }}>
          <div className="flex gap-6 text-sm" style={{ color: '#2D5016' }}>
            <Link to="/nanny/privacy" className="underline">
              Privacy Policy
            </Link>
            <Link to="/nanny" className="underline">
              Back to Nanny
            </Link>
          </div>
        </div>
      </div>
    </div>
  );
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <section className="mb-10">
      <h2 className="mb-4 text-xl font-semibold" style={{ color: '#2D5016' }}>
        {title}
      </h2>
      <div className="space-y-2 leading-relaxed text-gray-700">{children}</div>
    </section>
  );
}
