import { getEnv } from '~/lib/.server/env';

interface SendEmailOptions {
  to: string;
  subject: string;
  html: string;
  from?: string;
}

interface EmailResult {
  success: boolean;
  messageId?: string;
  mockMode: boolean;
}

export async function sendNannyEmail(opts: SendEmailOptions): Promise<EmailResult> {
  const resendKey = getEnv('RESEND_API_KEY');
  const convexSiteUrl = getEnv('CONVEX_SITE_URL') ?? getEnv('VITE_CONVEX_SITE_URL');

  if (!resendKey || !convexSiteUrl) {
    console.log('[Nanny Email] Mock mode — RESEND_API_KEY or CONVEX_SITE_URL not set');
    return { success: true, mockMode: true };
  }

  const from = opts.from ?? 'Nanny Kitchen OS <noreply@nanny.kitchen>';

  try {
    const res = await fetch(`${convexSiteUrl}/resend-proxy/emails`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        Authorization: `Bearer ${resendKey}`,
      },
      body: JSON.stringify({
        from,
        to: [opts.to],
        subject: opts.subject,
        html: opts.html,
      }),
    });

    if (!res.ok) {
      const text = await res.text();
      console.error('[Nanny Email] Send failed:', text);
      return { success: false, mockMode: false };
    }

    const data = (await res.json()) as { id?: string };
    return { success: true, messageId: data.id, mockMode: false };
  } catch (err) {
    console.error('[Nanny Email] Error:', err);
    return { success: false, mockMode: false };
  }
}

export function buildRunbookEmailHtml(runbook: Record<string, unknown>, brandName: string): string {
  const title = String(runbook.title ?? 'Service Runbook');
  const phases = Array.isArray(runbook.phases) ? runbook.phases : [];

  const phaseHtml = phases
    .map((phase: unknown) => {
      const p = phase as Record<string, unknown>;
      const tasks = Array.isArray(p.tasks) ? p.tasks : [];
      const taskHtml = tasks
        .map((task: unknown) => {
          const t = task as Record<string, unknown>;
          return `<tr>
            <td style="padding:8px 12px;border-bottom:1px solid #f0f0e8;">
              <span style="display:inline-block;width:14px;height:14px;border:1.5px solid #2D5016;border-radius:3px;margin-right:8px;vertical-align:middle;"></span>
              ${String(t.taskName ?? t.task ?? '')}
            </td>
          </tr>`;
        })
        .join('');

      return `
        <tr>
          <td style="padding:20px 0 8px 0;">
            <p style="margin:0;font-size:11px;font-weight:700;text-transform:uppercase;letter-spacing:0.1em;color:#2D5016;">${String(p.phaseName ?? '')}</p>
          </td>
        </tr>
        ${taskHtml}
      `;
    })
    .join('');

  return `<!DOCTYPE html>
<html>
<head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"></head>
<body style="margin:0;padding:0;background:#FAFAF7;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif;">
  <table width="100%" cellpadding="0" cellspacing="0" style="background:#FAFAF7;padding:40px 20px;">
    <tr><td align="center">
      <table width="600" cellpadding="0" cellspacing="0" style="background:#fff;border-radius:16px;overflow:hidden;border:1px solid #e8f0e0;">
        <!-- Header -->
        <tr>
          <td style="background:#2D5016;padding:24px 32px;">
            <p style="margin:0;color:rgba(255,255,255,0.6);font-size:11px;font-weight:600;text-transform:uppercase;letter-spacing:0.1em;">${brandName}</p>
            <h1 style="margin:8px 0 0;color:#fff;font-size:22px;font-weight:700;">${title}</h1>
          </td>
        </tr>
        <!-- Body -->
        <tr>
          <td style="padding:32px;">
            <table width="100%" cellpadding="0" cellspacing="0">
              ${phaseHtml}
            </table>
          </td>
        </tr>
        <!-- Footer -->
        <tr>
          <td style="padding:20px 32px;border-top:1px solid #f0f0e8;">
            <p style="margin:0;font-size:11px;color:#999;">Generated by ${brandName} · Plant-Based Hospitality Intelligence</p>
          </td>
        </tr>
      </table>
    </td></tr>
  </table>
</body>
</html>`;
}

export function buildMenuEmailHtml(menu: Record<string, unknown>, brandName: string): string {
  const title = String(menu.title ?? 'Menu');
  const description = String(menu.description ?? '');
  const courses = Array.isArray(menu.courses) ? menu.courses : [];

  const courseHtml = courses
    .map((course: unknown) => {
      const c = course as Record<string, unknown>;
      const dishes = Array.isArray(c.dishes) ? c.dishes : [];
      const dishHtml = dishes
        .map((dish: unknown) => {
          const d = dish as Record<string, unknown>;
          return `<tr>
            <td style="padding:12px 0;border-bottom:1px solid #f0f0e8;">
              <p style="margin:0;font-weight:600;font-size:14px;color:#1A1A18;">${String(d.name ?? '')}</p>
              ${d.description ? `<p style="margin:4px 0 0;font-size:12px;color:#666;">${String(d.description)}</p>` : ''}
              ${d.cuisineOrigin ? `<p style="margin:4px 0 0;font-size:11px;color:#2D5016;">${String(d.cuisineOrigin)}</p>` : ''}
            </td>
          </tr>`;
        })
        .join('');

      return `
        <tr><td style="padding:20px 0 8px;"><p style="margin:0;font-size:11px;font-weight:700;text-transform:uppercase;letter-spacing:0.1em;color:#2D5016;">${String(c.courseName ?? '')}</p></td></tr>
        ${dishHtml}
      `;
    })
    .join('');

  return `<!DOCTYPE html>
<html>
<head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"></head>
<body style="margin:0;padding:0;background:#FAFAF7;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif;">
  <table width="100%" cellpadding="0" cellspacing="0" style="background:#FAFAF7;padding:40px 20px;">
    <tr><td align="center">
      <table width="600" cellpadding="0" cellspacing="0" style="background:#fff;border-radius:16px;overflow:hidden;border:1px solid #e8f0e0;">
        <tr>
          <td style="background:#2D5016;padding:24px 32px;">
            <p style="margin:0;color:rgba(255,255,255,0.6);font-size:11px;font-weight:600;text-transform:uppercase;letter-spacing:0.1em;">${brandName}</p>
            <h1 style="margin:8px 0 0;color:#fff;font-size:22px;font-weight:700;">${title}</h1>
            ${description ? `<p style="margin:8px 0 0;color:rgba(255,255,255,0.7);font-size:13px;">${description}</p>` : ''}
          </td>
        </tr>
        <tr>
          <td style="padding:32px;">
            <table width="100%" cellpadding="0" cellspacing="0">${courseHtml}</table>
          </td>
        </tr>
        <tr>
          <td style="padding:20px 32px;border-top:1px solid #f0f0e8;">
            <p style="margin:0;font-size:11px;color:#999;">Generated by ${brandName} · Plant-Based Hospitality Intelligence</p>
          </td>
        </tr>
      </table>
    </td></tr>
  </table>
</body>
</html>`;
}
